/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Base_1: THREE.Mesh
    Base_2: THREE.Mesh
    Base_3: THREE.Mesh
    Base_4: THREE.Mesh
    Pitch_1: THREE.Mesh
    Pitch_2: THREE.Mesh
    Pitch_3: THREE.Mesh
    Yaw_1: THREE.Mesh
    Yaw_2: THREE.Mesh
    Yaw_3: THREE.Mesh
    Roll_1: THREE.Mesh
    Roll_2: THREE.Mesh
    Roll_3: THREE.Mesh
    Roll_4: THREE.Mesh
    Roll_5: THREE.Mesh
    Roll_6: THREE.Mesh
    Roll_7: THREE.Mesh
  }
  materials: {
    Black: THREE.MeshStandardMaterial
    Blue: THREE.MeshStandardMaterial
    Red: THREE.MeshStandardMaterial
    Orange: THREE.MeshStandardMaterial
    Metalic: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Orange: THREE.MeshStandardMaterial
    Metalic: THREE.MeshStandardMaterial
    Red: THREE.MeshStandardMaterial
    Green: THREE.MeshStandardMaterial
    Brown: THREE.MeshStandardMaterial
    MFD: THREE.MeshStandardMaterial
  }
}

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/NGS-360-3-B.glb') as GLTFResult
  const instances = useMemo(
    () => ({
      Base: nodes.Base_1,
      Base1: nodes.Base_2,
      Base2: nodes.Base_3,
      Base3: nodes.Base_4,
      Pitch: nodes.Pitch_1,
      Pitch1: nodes.Pitch_2,
      Pitch2: nodes.Pitch_3,
      Yaw: nodes.Yaw_1,
      Yaw1: nodes.Yaw_2,
      Yaw2: nodes.Yaw_3,
      Roll: nodes.Roll_1,
      Roll1: nodes.Roll_2,
      Roll2: nodes.Roll_3,
      Roll3: nodes.Roll_4,
      Roll4: nodes.Roll_5,
      Roll5: nodes.Roll_6,
      Roll6: nodes.Roll_7,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.Base />
      <instances.Base1 />
      <instances.Base2 />
      <instances.Base3 />
      <group position={[0, 1.8085, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.00109}>
        <instances.Pitch />
        <instances.Pitch1 />
        <instances.Pitch2 />
        <group position={[0, 0, -0.00012]} rotation={[-3.1413, -1.57056, 0]}>
          <instances.Yaw />
          <instances.Yaw1 />
          <instances.Yaw2 />
          <group
            position={[-0.00012, 0, 0]}
            rotation={[-3.14134, 0, -1.57109]}
            scale={[919.11353, 919.11365, 919.11359]}>
            <instances.Roll />
            <instances.Roll1 />
            <instances.Roll2 />
            <instances.Roll3 />
            <instances.Roll4 />
            <instances.Roll5 />
            <instances.Roll6 />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/NGS-360-3-B.glb')
