/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/NGS-360-3-B.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Base_1.geometry} material={materials.Black} />
      <mesh castShadow receiveShadow geometry={nodes.Base_2.geometry} material={materials.Blue} />
      <mesh castShadow receiveShadow geometry={nodes.Base_3.geometry} material={materials.Red} />
      <mesh castShadow receiveShadow geometry={nodes.Base_4.geometry} material={materials.Orange} />
      <group position={[0, 1.809, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pitch_1.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pitch_2.geometry}
          material={materials.Orange}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pitch_3.geometry}
          material={materials.Metalic}
        />
        <group rotation={[-3.141, -1.571, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Yaw_1.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Yaw_2.geometry}
            material={materials.Orange}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Yaw_3.geometry}
            material={materials.Metalic}
          />
          <group rotation={[-3.141, 0, -1.571]} scale={919.114}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roll_1.geometry}
              material={materials.Black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roll_2.geometry}
              material={materials.Orange}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roll_3.geometry}
              material={materials.Metalic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roll_4.geometry}
              material={materials.Red}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roll_5.geometry}
              material={materials.Green}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roll_6.geometry}
              material={materials.Brown}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roll_7.geometry}
              material={materials.MFD}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/NGS-360-3-B.glb')


rembrandt

city
Made by @NikkitaFTW & contributors inspired by the gltfjsx cli

