/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Amber.glb --transform --shadows --keepgroups --keepmeshes --simplify 
Files: Amber.glb [110.04MB] > Amber-transformed.glb [7.02MB] (94%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Amber(props) {
  const { nodes, materials } = useGLTF('/covisart/models/Amber-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh castShadow  geometry={nodes.Bang.geometry} material={materials.Hair_Transparency} scale={0.01} />
        <mesh castShadow  geometry={nodes.Boots.geometry} material={materials.Boots} scale={0.01} />
        <mesh castShadow  geometry={nodes.Bun.geometry} material={materials.Hair_Transparency} scale={0.01} />
        <group scale={0.01}>
          <mesh castShadow  geometry={nodes.Camila_Brow_1.geometry} material={materials.Female_Brow_Transparency} />
          <mesh castShadow  geometry={nodes.Camila_Brow_2.geometry} material={materials.Female_Brow_Base_Transparency} />
        </group>
        <group scale={0.01}>
          <mesh castShadow  geometry={nodes.CC_Base_Body_1.geometry} material={materials.Std_Skin_Head} />
          <mesh castShadow  geometry={nodes.CC_Base_Body_2.geometry} material={materials.Std_Skin_Body} />
          <mesh castShadow  geometry={nodes.CC_Base_Body_3.geometry} material={materials.Std_Skin_Arm} />
          <mesh castShadow  geometry={nodes.CC_Base_Body_4.geometry} material={materials.Std_Skin_Leg} />
          <mesh castShadow  geometry={nodes.CC_Base_Body_5.geometry} material={materials.Std_Nails} />
          <mesh castShadow  geometry={nodes.CC_Base_Body_6.geometry} material={materials.Std_Eyelash} />
        </group>
        <group scale={0.01}>
          <mesh castShadow  geometry={nodes.CC_Base_Eye_1.geometry} material={materials.Std_Eye_R} />
          <mesh castShadow  geometry={nodes.CC_Base_Eye_2.geometry} material={materials.Std_Cornea_R} />
          <mesh castShadow  geometry={nodes.CC_Base_Eye_3.geometry} material={materials.Std_Eye_L} />
          <mesh castShadow  geometry={nodes.CC_Base_Eye_4.geometry} material={materials.Std_Cornea_R} />
        </group>
        <group scale={0.01}>
          <mesh castShadow  geometry={nodes.CC_Base_Teeth_1.geometry} material={materials.Std_Upper_Teeth} />
          <mesh castShadow  geometry={nodes.CC_Base_Teeth_2.geometry} material={materials.Std_Lower_Teeth} />
        </group>
        <mesh castShadow  geometry={nodes.Crop_T_Shirt.geometry} material={materials.Female_T_Shirt} scale={0.01} />
        <mesh castShadow  geometry={nodes.Hair_Base.geometry} material={materials.Hair_Transparency} scale={0.01} />
        <mesh castShadow  geometry={nodes.Jeans.geometry} material={materials.Jeans} scale={0.01} />
        <mesh castShadow  geometry={nodes.Punk_Leather_Jacket.geometry} material={materials.Punk_Leather_jacket} scale={0.01} />
        <mesh castShadow  geometry={nodes.Real_Hair.geometry} material={materials.Hair_Transparency} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/covisart/models/Amber-transformed.glb')
