/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 female.glb --transform --shadows --keepgroups --keepmeshes 
Files: female.glb [18.6MB] > female-transformed.glb [204.31KB] (99%)
*/

import React from 'react'
import { useGLTF} from '@react-three/drei'

export function Female(props) {
  const { nodes, materials } = useGLTF('/covisart/models/female-transformed.glb')

  return (
    <group {...props} dispose={null}>
      <group>
      <mesh castShadow receiveShadow geometry={nodes.rp_sophia_animated_003_idling_geo.geometry} 
        material={materials.rp_sophia_animated_003_mat} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/covisart/models/female-transformed.glb')
