/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ForWeb.glb --transform --keepmaterials 
Files: ForWeb.glb [50.88MB] > C:\Users\TUNGUSKA-TUF\Documents\Github\SimulatorFrameCAD\glb\ForWeb-transformed.glb [9.01MB] (82%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/covisart/models/ForWeb-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DIN_125_M8_DIN_125_M8.geometry} material={materials.Bolts} position={[-1.191, 2.967, 0.025]} rotation={[2.522, -Math.PI / 6, -2.526]} scale={0.001} />
      <mesh geometry={nodes.DIN_912_M6_DIN_912_M6_x_25.geometry} material={materials.Bolts} position={[-0.033, 2.986, 0.027]} rotation={[-1.575, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.NG_A1K1_Varsayılan.geometry} material={materials.Metal} position={[0, 3.021, -0.006]} rotation={[-1.575, 0, -Math.PI]} scale={0.001} />
      <mesh geometry={nodes['NG_A1P150x150_Default<As_Machined>'].geometry} material={materials.MainColor} position={[1.228, 3.072, -0.006]} rotation={[-0.004, 0, -Math.PI]} scale={0.001} />
      <mesh geometry={nodes.Inside.geometry} material={materials.GRAY54} position={[1.943, 1.662, 0]} rotation={[-2.154, Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes.OutSide.geometry} material={materials.MainColor} position={[1.853, 1.662, 0]} rotation={[2.605, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes['LA36_P15-0361247'].geometry} material={materials.ActuatorBody} position={[0.001, 0.927, -0.392]} rotation={[-1.575, -0.001, 3.141]} scale={0.001} />
      <mesh geometry={nodes.LA36_P2_2500189.geometry} material={materials.ActuatorBody} position={[0.001, 0.959, -0.392]} rotation={[-0.004, -0.001, 0.001]} scale={0.001} />
      <group position={[0, 1.694, 0.224]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Cockpit.geometry} material={materials.Carbon} />
        <mesh geometry={nodes.Cockpit_1.geometry} material={materials.MFD} />
      </group>
      <group position={[0.022, 1.777, -0.619]} rotation={[1.993, -1.57, 1.997]} scale={0.001}>
        <mesh geometry={nodes.EjSeat_1.geometry} material={materials.LIGHTSALMON3} />
        <mesh geometry={nodes.EjSeat_2.geometry} material={materials.Fabric} />
        <mesh geometry={nodes.EjSeat_3.geometry} material={materials.RED} />
        <mesh geometry={nodes.EjSeat_4.geometry} material={materials.MainColor} />
        <mesh geometry={nodes.EjSeat_5.geometry} material={materials.Copper} />
        <mesh geometry={nodes.EjSeat_6.geometry} material={materials.ROSYBROWN} />
        <mesh geometry={nodes.EjSeat_7.geometry} material={materials.Metal} />
      </group>
      <mesh geometry={nodes.DIN_912_M8_x_25_DIN_912_M8_x_25.geometry} material={materials.LIGHTPINK4} position={[0.039, 1.758, 1.244]} rotation={[-1.575, -0.001, 1.57]} scale={0.001} />
      <mesh geometry={nodes['18PTH'].geometry} material={materials.GRAY75} position={[0.133, 1.302, 1.145]} rotation={[2.011, -1.57, -1.127]} scale={0.001} />
      <mesh geometry={nodes.HGH55C_左封_temp.geometry} material={materials.RED} position={[0.075, 1.376, 1.15]} rotation={[2.011, -1.57, -1.127]} scale={0.001} />
      <mesh geometry={nodes['Intercontec-BEDC110NN00000101000^BEKCHOFF_AM8062-xL11001'].geometry} material={materials.LAVENDERBLUSH4} position={[-0.001, 2.047, 0.922]} rotation={[-1.575, -0.001, -0.001]} scale={0.001} />
      <mesh geometry={nodes['DIN_982_M10_DIN_982_-_M10004'].geometry} material={materials.DODGERBLUE3} position={[0.058, 1.609, 1.246]} rotation={[1.567, -0.294, 0.001]} scale={0.001} />
      <mesh geometry={nodes['skf_bearing_7210_be-2rzp_2_03002'].geometry} material={materials.SIENNA} position={[0.001, 1.658, -1.224]} rotation={[-1.575, -0.001, -1.571]} scale={0.001} />
      <group position={[0.04, 0.417, 0.096]} rotation={[3.138, 0.001, -Math.PI]} scale={0.001}>
        <mesh geometry={nodes.DIN_982_M8_DIN_982_M8_1.geometry} material={materials.GRAY90} />
        <mesh geometry={nodes.DIN_982_M8_DIN_982_M8_2.geometry} material={materials.DODGERBLUE3} />
      </group>
      <mesh geometry={nodes.NG_A1S5H2_Marked_Labled.geometry} material={materials.FIREBRICK} position={[0.001, 2.609, -1.144]} rotation={[2.352, 0, -3.141]} scale={0.001} />
      <mesh geometry={nodes.NG_P1H5.geometry} material={materials.RED} position={[2.095, 1.647, -0.12]} scale={0.001} />
      <mesh geometry={nodes.NG_T1S13H2.geometry} material={materials.BLUE} position={[2.648, 1.785, -0.125]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.Percin_Somun_M10.geometry} material={materials.Metal} position={[1.842, 0.27, 0.038]} rotation={[-0.157, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes['snh_511-1_tg_05'].geometry} material={materials.GRAY42} position={[-1.803, 1.593, -0.127]} rotation={[0, -Math.PI / 2, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/ForWeb-transformed.glb')
