/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 model.glb --transform 
Files: model.glb [118.02MB] > model-transformed.glb [36.82MB] (69%)
*/

import React, { useRef, useState } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
export function Model(props) {
  const ref = useRef()
  // Hold state for hovered and clicked events
  const [hovered, hover] = useState(false)
  const [clicked, click] = useState(false)
  // Subscribe this component to the render-loop, rotate the mesh every frame
  const { nodes, materials } = useGLTF('/model-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={9.81} near={5.189} fov={39.598} position={[3.726, 1.652, 6.508]} rotation={[-0.097, 0.53, 0.049]} />
      <mesh geometry={nodes.NG_Axis_3_CarbonFiberKaplama.geometry} material={materials.PaletteMaterial001} position={[-0.171, 0.905, 0.072]}>
      <meshPhysicalMaterial color="black" />
      </mesh>
      <instancedMesh args={[nodes['DIN_982_M8-mesh'].geometry, materials.PaletteMaterial001, 352]} instanceMatrix={nodes['DIN_982_M8-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_912_M12(DIN_912_M12_x_25)-mesh'].geometry, materials.PaletteMaterial001, 22]} instanceMatrix={nodes['DIN_912_M12(DIN_912_M12_x_25)-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_125_M12-mesh'].geometry, materials.PaletteMaterial001, 92]} instanceMatrix={nodes['DIN_125_M12-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_912_M8-mesh'].geometry, materials.PaletteMaterial001, 12]} instanceMatrix={nodes['DIN_912_M8-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_912_M8_x_25-mesh'].geometry, materials.PaletteMaterial001, 624]} instanceMatrix={nodes['DIN_912_M8_x_25-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_912_M8_x_10(DIN_912_M8_x_30_---_30N)-mesh'].geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes['DIN_912_M8_x_10(DIN_912_M8_x_30_---_30N)-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_912_M8_x_20-mesh'].geometry, materials.PaletteMaterial001, 60]} instanceMatrix={nodes['DIN_912_M8_x_20-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_127_M8-mesh'].geometry, materials.PaletteMaterial001, 84]} instanceMatrix={nodes['DIN_127_M8-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_125_M8-mesh'].geometry, materials.PaletteMaterial001, 1024]} instanceMatrix={nodes['DIN_125_M8-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['3210-bd-xl-2hrs-tvh-mesh'].geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes['3210-bd-xl-2hrs-tvh-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['3210-bd-xl-2hrs-tvh-mesh_1'].geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes['3210-bd-xl-2hrs-tvh-mesh_1'].instanceMatrix} />
      <instancedMesh args={[nodes['3210-bd-xl-2hrs-tvh-mesh_2'].geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes['3210-bd-xl-2hrs-tvh-mesh_2'].instanceMatrix} />
      <instancedMesh args={[nodes['3210-bd-xl-2hrs-tvh-mesh_3'].geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes['3210-bd-xl-2hrs-tvh-mesh_3'].instanceMatrix} />
      <instancedMesh args={[nodes['NG_A3BP-mesh'].geometry, materials.PaletteMaterial001, 8]} instanceMatrix={nodes['NG_A3BP-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['NG_S1H3-mesh'].geometry, materials.PaletteMaterial001, 16]} instanceMatrix={nodes['NG_S1H3-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['ISO_7380_M6_x_10(ISO_7380_M6_x_10_)-mesh'].geometry, materials.PaletteMaterial001, 72]} instanceMatrix={nodes['ISO_7380_M6_x_10(ISO_7380_M6_x_10_)-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_912_M6-mesh'].geometry, materials.PaletteMaterial001, 52]} instanceMatrix={nodes['DIN_912_M6-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['NG_A1K2-mesh'].geometry, materials.PaletteMaterial001, 12]} instanceMatrix={nodes['NG_A1K2-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['NG_A1K1-mesh'].geometry, materials.PaletteMaterial001, 12]} instanceMatrix={nodes['NG_A1K1-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['NG_A1S5H2-mesh'].geometry, materials.PaletteMaterial001, 34]} instanceMatrix={nodes['NG_A1S5H2-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['NG_A2S3H5-mesh'].geometry, materials.PaletteMaterial001, 12]} instanceMatrix={nodes['NG_A2S3H5-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['NG_A1S3H5-mesh'].geometry, materials.PaletteMaterial001, 8]} instanceMatrix={nodes['NG_A1S3H5-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['NG_A2S1H5-mesh'].geometry, materials.PaletteMaterial001, 8]} instanceMatrix={nodes['NG_A2S1H5-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['NG_A1S4H5-mesh'].geometry, materials.PaletteMaterial001, 8]} instanceMatrix={nodes['NG_A1S4H5-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['NG_A1S1H3-mesh'].geometry, materials.PaletteMaterial001, 16]} instanceMatrix={nodes['NG_A1S1H3-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_912_M10(DIN_912_M10_x_30)-mesh'].geometry, materials.PaletteMaterial001, 56]} instanceMatrix={nodes['DIN_912_M10(DIN_912_M10_x_30)-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_912_M12(DIN_912_M12_x_60)-mesh'].geometry, materials.PaletteMaterial001, 12]} instanceMatrix={nodes['DIN_912_M12(DIN_912_M12_x_60)-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_982_M10-mesh'].geometry, materials.PaletteMaterial001, 78]} instanceMatrix={nodes['DIN_982_M10-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_125_M10-mesh'].geometry, materials.PaletteMaterial001, 158]} instanceMatrix={nodes['DIN_125_M10-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_912_M12(DIN_912__M12_x_130)-mesh'].geometry, materials.PaletteMaterial001, 22]} instanceMatrix={nodes['DIN_912_M12(DIN_912__M12_x_130)-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['NG_T1S16H4-mesh'].geometry, materials.PaletteMaterial001, 12]} instanceMatrix={nodes['NG_T1S16H4-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_912_M10(DIN_912_M10_x_65)-mesh'].geometry, materials.PaletteMaterial001, 10]} instanceMatrix={nodes['DIN_912_M10(DIN_912_M10_x_65)-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_982_-_M12-mesh'].geometry, materials.PaletteMaterial001, 34]} instanceMatrix={nodes['DIN_982_-_M12-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_912_M10(DIN_912_M10_x_90)-mesh'].geometry, materials.PaletteMaterial001, 14]} instanceMatrix={nodes['DIN_912_M10(DIN_912_M10_x_90)-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['DIN_7991_M10_x_10-mesh'].geometry, materials.PaletteMaterial001, 38]} instanceMatrix={nodes['DIN_7991_M10_x_10-mesh'].instanceMatrix} />
      <instancedMesh args={[nodes['SKF_6012_2RS1_18-mesh'].geometry, materials.PaletteMaterial001, 56]} instanceMatrix={nodes['SKF_6012_2RS1_18-mesh'].instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/model-transformed.glb')
