/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 NGS-360.glb --transform -s --K --shadows 
Files: NGS-360.glb [648.6MB] > NGS-360-transformed.glb [31.08MB] (95%)
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/NGS-360-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <PerspectiveCamera makeDefault={false} far={9.543} near={5.455} fov={39.598} position={[-2.794, 1.155, -6.957]} rotation={[3.132, -0.377, 3.138]} />
        <mesh castShadow receiveShadow geometry={nodes.color000.geometry} material={materials['color:0:0:0']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color0128255.geometry} material={materials['color:0:128:255']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color014269.geometry} material={materials['color:0:142:69']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color02550.geometry} material={materials['color:0:255:0']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color112160251.geometry} material={materials['color:112:160:251']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color1112454.geometry} material={materials['color:11:124:54']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color12800.geometry} material={materials['color:128:0:0']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color1280128.geometry} material={materials['color:128:0:128']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color128128128.geometry} material={materials['color:128:128:128']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color1368986.geometry} material={materials['color:136:89:86']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color1394545.geometry} material={materials['color:139:45:45']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color141132136.geometry} material={materials['color:141:132:136']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color149149149.geometry} material={materials['color:149:149:149']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color163163175.geometry} material={materials['color:163:163:175']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color165158149.geometry} material={materials['Paint Metallic Dark Cool Grey #2']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color166158149.geometry} material={materials['Aluminum Polished #1']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color170178195.geometry} material={materials['color:170:178:195']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color173195207.geometry} material={materials['color:173:195:207']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color175175175.geometry} material={materials['color:175:175:175']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color178178178.geometry} material={materials['color:178:178:178']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color1719284.geometry} material={materials['color:17:192:84']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color191191191.geometry} material={materials['color:191:191:191']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color19714327.geometry} material={materials['color:197:143:27']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color197192187.geometry} material={materials['Paint Metallic Dark Cool Grey #2']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color202209237.geometry} material={materials['color:202:209:237']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color204204204.geometry} material={materials['color:204:204:204']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color20760.geometry} material={materials['color:207:6:0']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color216214214.geometry} material={materials['color:216:214:214']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color219214192.geometry} material={materials['color:219:214:192']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color229229229.geometry} material={materials['color:229:229:229']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color229233236.geometry} material={materials['color:229:233:236']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color229234236.geometry} material={materials['color:229:234:236']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color241235237.geometry} material={materials['color:241:235:237']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color2461550.geometry} material={materials['color:246:155:0']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color2466565.geometry} material={materials['color:246:65:65']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color25500.geometry} material={materials['color:255:0:0']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color25512422.geometry} material={materials['color:255:124:22']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color2551280.geometry} material={materials['color:255:128:0']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color255128255.geometry} material={materials['color:255:128:255']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color25525146.geometry} material={materials['color:255:251:46']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color2552550.geometry} material={materials['color:255:255:0']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color255255255.geometry} material={materials['color:255:255:255']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color515151.geometry} material={materials['color:51:51:51']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color64128128.geometry} material={materials['color:64:128:128']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color646464.geometry} material={materials['color:64:64:64']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color7216984.geometry} material={materials['color:72:169:84']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color74168129.geometry} material={materials['color:74:168:129']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color767676.geometry} material={materials['color:76:76:76']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color816353.geometry} material={materials['color:81:63:53']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color828282.geometry} material={materials['color:82:82:82']} position={[-0.16, 0.012, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.color949494.geometry} material={materials['color:94:94:94']} position={[-0.16, 0.012, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/NGS-360-transformed.glb')
