/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 NGS_GLT_V2.glb --transform --shadows --keepgroups --keepmeshes 
Files: NGS_GLT_V2.glb [113.35MB] > NGS_GLT_V2-transformed.glb [7.84MB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF, AccumulativeShadows,RandomizedLight } from '@react-three/drei'
import { useSnapshot } from 'valtio'
import { state } from '../store'
import { useFrame } from '@react-three/fiber'
import { easing } from 'maath'

export function Model(props) {
  const { nodes, materials } = useGLTF('/covisart/models/NGS_GLT_V2-transformed.glb')
  materials.Paint.color.r =1;
  materials.Paint.color.g =1;
  materials.Paint.color.b =0;
  const snap = useSnapshot(state)
  useFrame((state, delta) => {
    easing.dampC(materials.Paint.color, snap.color, 0.0, delta)
  })
  //materials.Paint.color = "green";
  return (
    <group {...props} dispose={null}>
      <group>
        {
          nodes[snap.motor] != null && <mesh castShadow geometry={nodes[snap.motor].geometry} material={materials.Metal} />
        }
        <mesh castShadow geometry={nodes.KOFON_KPL120.geometry} material={materials.Metal} />
        <mesh castShadow geometry={nodes.NG_A3BP.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A3KM.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A3S2H5.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A3S6H2.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.Vidalar_3.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A1K1007.geometry} material={materials.Metal} />
        <mesh castShadow geometry={nodes.NG_A1K2003.geometry} material={materials.Metal} />
        <mesh castShadow geometry={nodes.NG_A1S3H5001.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A1S5H2001.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A2MM001.geometry} material={materials.Metal} />
        <mesh castShadow geometry={nodes.NG_A2MS001.geometry} material={materials.Metal} />
        <mesh castShadow geometry={nodes.NG_A2P120x120x3_U2510.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A2P120x120x3_U2550005.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A2P120x120x3_U2550_DRIVER001.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A2S11H2DCR001.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A2S1H5009.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A2S7H2MCO001.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_S1H3005.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.Vidalar003.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A1K1009.geometry} material={materials.Metal} />
        <mesh castShadow geometry={nodes.NG_A1P120x120x3_U2220003.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A1P120x120x3_U2220007.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A1P120x200x3_U1220001.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A1P120x200x3_U1220007.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A1S2H5001.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A1S2H5007.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_A1S5H2067.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_S1H3041.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.Vidalar.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.LP_20.geometry} material={materials.connector} />
        <mesh castShadow geometry={nodes.NG_P1H5.geometry} material={materials.led} />
        <mesh castShadow geometry={nodes.NG_T1S13H2.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_T1S14H2.geometry} material={materials.Paint} />
        <mesh castShadow geometry={nodes.NG_T1S2H15.geometry} material={materials.Paint} />
        <group>
          <mesh castShadow   geometry={nodes['RJ45_cover_orange-mesh'].geometry} material={materials.orange} />
          <mesh castShadow   geometry={nodes['RJ45_cover_orange-mesh_1'].geometry} material={materials.connector} />
        </group>
        <mesh castShadow   geometry={nodes.Vidalar_Platform.geometry} material={materials.Paint} />
      </group>
    </group>
  )
}
useGLTF.preload('/covisart/models/NGS_GLT_V2-transformed.glb')
