/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 NGS_GLT_V2.glb --transform --shadows --keepgroups --keepmeshes --keepmaterials 
Files: NGS_GLT_V2.glb [117.38MB] > NGS_GLT_V2-transformed.glb [11.95MB] (90%)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Ngs_GLT({ url, ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(url)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="NGS_Platform">
          <mesh name="LP_20" castShadow receiveShadow geometry={nodes.LP_20.geometry} material={materials.connector} />
          <mesh name="NG_T1S13H2" castShadow receiveShadow geometry={nodes.NG_T1S13H2.geometry} material={materials.Kutu} />
          <mesh name="NG_T1S14H2" castShadow receiveShadow geometry={nodes.NG_T1S14H2.geometry} material={materials.Cover_1} />
          <mesh name="NG_T1S2H15" castShadow receiveShadow geometry={nodes.NG_T1S2H15.geometry} material={materials.Platform} />
          <group name="RJ45">
            <mesh name="RJ45_1" castShadow receiveShadow geometry={nodes.RJ45_1.geometry} material={materials.orange} />
            <mesh name="RJ45_2" castShadow receiveShadow geometry={nodes.RJ45_2.geometry} material={materials.connector} />
          </group>
          <mesh name="Vidalar_Platform" castShadow receiveShadow geometry={nodes.Vidalar_Platform.geometry} material={materials.Paint} />
        </group>
        <group name="Ruller">
          <mesh name="Cube" castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.Line} />
          <mesh name="Cube001" castShadow receiveShadow geometry={nodes.Cube001.geometry} material={materials.LineBlue} />
          <mesh name="Cube002" castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials.Line} />
          <mesh name="Cube003" castShadow receiveShadow geometry={nodes.Cube003.geometry} material={materials.Line} />
          <mesh name="Cube004" castShadow receiveShadow geometry={nodes.Cube004.geometry} material={materials.Line} />
          <mesh name="Cube005" castShadow receiveShadow geometry={nodes.Cube005.geometry} material={materials.LineBlue} />
          <mesh name="Cube006" castShadow receiveShadow geometry={nodes.Cube006.geometry} material={materials.Line} />
          <mesh name="Cube007" castShadow receiveShadow geometry={nodes.Cube007.geometry} material={materials.Line} />
          <mesh name="Cube008" castShadow receiveShadow geometry={nodes.Cube008.geometry} material={materials.LineBlue} />
          <mesh name="Text" castShadow receiveShadow geometry={nodes.Text.geometry} material={materials.Front_Text} />
        </group>
        <group name="NG_Axis_3">
          <mesh name="BECKHOFF_AM8552" castShadow receiveShadow geometry={nodes.BECKHOFF_AM8552.geometry} material={materials.Metal} />
          <mesh name="KOFON_KPL120" castShadow receiveShadow geometry={nodes.KOFON_KPL120.geometry} material={materials.Metal} />
          <mesh name="NG_A3BP" castShadow receiveShadow geometry={nodes.NG_A3BP.geometry} material={materials.Paint} />
          <mesh name="NG_A3KM" castShadow receiveShadow geometry={nodes.NG_A3KM.geometry} material={materials.Metal} />
          <mesh name="NG_A3S2H5" castShadow receiveShadow geometry={nodes.NG_A3S2H5.geometry} material={materials.NGS_Axis_3} />
          <mesh name="NG_A3S6H2" castShadow receiveShadow geometry={nodes.NG_A3S6H2.geometry} material={materials.NGS_Axis_3_Box} />
          <mesh name="Vidalar_3" castShadow receiveShadow geometry={nodes.Vidalar_3.geometry} material={materials.Paint} />
        </group>
        <group name="NG_Axis_1">
          <mesh name="NG_A1K1009" castShadow receiveShadow geometry={nodes.NG_A1K1009.geometry} material={materials.Metal} />
          <mesh name="NG_A1P120x120x3_U2220003" castShadow receiveShadow geometry={nodes.NG_A1P120x120x3_U2220003.geometry} material={materials.Paint} />
          <mesh name="NG_A1P120x120x3_U2220007" castShadow receiveShadow geometry={nodes.NG_A1P120x120x3_U2220007.geometry} material={materials.Paint} />
          <mesh name="NG_A1P120x200x3_U1220001" castShadow receiveShadow geometry={nodes.NG_A1P120x200x3_U1220001.geometry} material={materials.Paint} />
          <mesh name="NG_A1P120x200x3_U1220007" castShadow receiveShadow geometry={nodes.NG_A1P120x200x3_U1220007.geometry} material={materials.Paint} />
          <mesh name="NG_A1S2H5001" castShadow receiveShadow geometry={nodes.NG_A1S2H5001.geometry} material={materials.NGS_AXIS_1_F} />
          <mesh name="NG_A1S2H5007" castShadow receiveShadow geometry={nodes.NG_A1S2H5007.geometry} material={materials.NGS_AXIS_1_F} />
          <mesh name="NG_A1S5H2067" castShadow receiveShadow geometry={nodes.NG_A1S5H2067.geometry} material={materials.Paint} />
          <mesh name="NG_S1H3041" castShadow receiveShadow geometry={nodes.NG_S1H3041.geometry} material={materials.Paint} />
          <mesh name="Vidalar" castShadow receiveShadow geometry={nodes.Vidalar.geometry} material={materials.Paint} />
        </group>
        <group name="NG_Axis_2">
          <mesh name="NG_A1K1007" castShadow receiveShadow geometry={nodes.NG_A1K1007.geometry} material={materials.Metal} />
          <mesh name="NG_A1K2003" castShadow receiveShadow geometry={nodes.NG_A1K2003.geometry} material={materials.Metal} />
          <mesh name="NG_A1S5H2001" castShadow receiveShadow geometry={nodes.NG_A1S5H2001.geometry} material={materials.Paint} />
          <mesh name="NG_A2MM001" castShadow receiveShadow geometry={nodes.NG_A2MM001.geometry} material={materials.Metal} />
          <mesh name="NG_A2MS001" castShadow receiveShadow geometry={nodes.NG_A2MS001.geometry} material={materials.Metal} />
          <mesh name="NG_A2P120x120x3_U2510" castShadow receiveShadow geometry={nodes.NG_A2P120x120x3_U2510.geometry} material={materials.Paint} />
          <mesh name="NG_A2P120x120x3_U2550005" castShadow receiveShadow geometry={nodes.NG_A2P120x120x3_U2550005.geometry} material={materials.Paint} />
          <mesh name="NG_A2P120x120x3_U2550_DRIVER001" castShadow receiveShadow geometry={nodes.NG_A2P120x120x3_U2550_DRIVER001.geometry} material={materials.Paint} />
          <mesh name="NG_A2S11H2DCR001" castShadow receiveShadow geometry={nodes.NG_A2S11H2DCR001.geometry} material={materials.NGS_Axis_2_Covier} />
          <mesh name="NG_A2S1H5" castShadow receiveShadow geometry={nodes.NG_A2S1H5.geometry} material={materials.NGS_Axis_2} />
          <mesh name="NG_A2S1H52" castShadow receiveShadow geometry={nodes.NG_A2S1H52.geometry} material={materials.NGS_Axis_2} />
          <mesh name="NG_A2S7H2MCO001" castShadow receiveShadow geometry={nodes.NG_A2S7H2MCO001.geometry} material={materials.NGS_Axis_2_Box} />
          <mesh name="NG_S1H3005" castShadow receiveShadow geometry={nodes.NG_S1H3005.geometry} material={materials.Paint} />
          <mesh name="Vidalar003" castShadow receiveShadow geometry={nodes.Vidalar003.geometry} material={materials.Paint} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/NGS_GLT_V2-transformed.glb')
